- name: Add load balancer to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: '{{ external_ip }} otus.internal'
    state: present

- name: Load tasks file with tune tasks based on the OS type
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
