- name: Create a wordpress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: "{{ mysql_socket }}"
    login_user: "{{ mysql_username }}"
    login_password: "{{ mysql_password }}"
  notify: restore_dump

- name: Create wordpress user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    host: "%.internal"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_unix_socket: "{{ mysql_socket }}"
    login_user: "{{ mysql_username }}"
    login_password: "{{ mysql_password }}"