[template]
prefix = "/db/main"
owner = "root"
mode = "0644"
src = "pgbouncer.tmpl"
dest = "/etc/pgbouncer/pgbouncer.ini"

reload_cmd = "systemctl reload pgbouncer"

keys = [
    "/members/","/leader"
]
