- name: Upgrade Debian Family OS packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  become: yes

- name: Check to see if we need a reboot (Debian)
  stat:
    path: /var/run/reboot-required
  register: needs_restart_debian_result
  changed_when: needs_restart_debian_result.stat.exists
  notify: reboot