# - name: Install EPEL repo.
#   ansible.builtin.dnf:
#     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
#     state: present

# - name: Import EPEL GPG key.
#   ansible.builtin.rpm_key:
#     key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
#     state: present

# - name: Install remi repo.
#   ansible.builtin.dnf:
#     name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
#     state: present

# - name: Import remi GPG key.
#   ansible.builtin.rpm_key:
#     key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
#     state: present

- name: Upgrade Red Hat Family OS packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Check to see if we need a reboot (RedHat)
  command: needs-restarting --reboothint
  register: needs_restart_redhat_result
  failed_when: needs_restart_redhat_result.rc > 1
  changed_when: needs_restart_redhat_result.rc == 1
  notify: reboot
