- name: Install mysql
  ansible.builtin.dnf:
    name:
      - mysql-server
      - python3-PyMySQL
    state: present

- name: Enable mysql service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Create a wordpress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  notify: restore_dump

- name: Create wordpress user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    host: "%.internal"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present