---
- name: Make dir for cert
  ansible.builtin.file:
    path: /etc/pki/otus
    state: directory
  tags: cert

- name: Make group for private key access
  ansible.builtin.group:
    name: tls-cert
    state: present

- name: Add etcd user to tls-cert group
  ansible.builtin.user:
    name: etcd
    groups:
      - tls-cert
    append: yes

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ pki_key_file }}"
    owner: root
    group: tls-cert
    mode: 0640
  tags: cert
  notify:
  - restart etcd

- name: Generate an OpenSSL Certificate Signing Request with subjectAltName extension
  community.crypto.openssl_csr:
    path: "{{ pki_csr_file }}"
    privatekey_path: "{{ pki_key_file }}"
    common_name: "{{ inventory_hostname }}"
    subject_alt_name: "DNS:{{ inventory_hostname }},IP:{{ ansible_host }},IP:127.0.0.1"
  tags: cert
  notify:
  - restart etcd

- name: Generate an OpenSSL certificate signed with your own CA certificate
  community.crypto.x509_certificate:
    path: "{{ pki_cert_file }}"
    csr_path: "{{ pki_csr_file }}"
    provider: ownca
    ownca_content: "{{ ca }}"
    ownca_privatekey_content: "{{ cakey }}"
  tags: cert
  notify:
  - restart etcd
