- name: Reboot
  reboot:
  become: yes
  listen: reboot
  any_errors_fatal: true

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  listen: reboot