zookeeper_port_client: 2181

zookeeper_version: 3.7.0
zookeeper_mirror: https://downloads.apache.org/zookeeper/
zookeeper_package: apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz

zookeeper_group: zookeeper
zookeeper_user: zookeeper

zookeeper_root_dir: /opt
zookeeper_log_dir: /var/log/zookeeper
zookeeper_install_dir: '{{ zookeeper_root_dir }}/apache-zookeeper-{{ zookeeper_version }}'
zookeeper_dir: '{{ zookeeper_root_dir }}/zookeeper'
zookeeper_data_dir: /var/lib/zookeeper
zookeeper_config_dir: /etc/zookeeper
zookeeper_config_file: zookeeper.cfg