#Upgrade bastion first
- hosts: bastion
  become: yes
  roles:
    - tune_all
    - upgrade

- hosts: all:!bastion
  become: yes
  roles:
    - tune_all
    - upgrade

- hosts: db
  become: yes
  roles:
    - wordpress_db

- hosts: app
  become: yes
  vars:
    wp_files_owner: apache
    wp_files_group: apache
  roles:
    - php_fpm
    - wordpress

- hosts: nginx
  become: yes
  vars:
    upstreams: "{{ groups['app'] | map('extract', hostvars, ['ansible_host']) | flatten }}"
    wp_files_owner: nginx
    wp_files_group: nginx
  roles:
    - nginx
    - wordpress